site_name: Shang Ma's Homepage
site_url: https://marshon36.github.io/
site_author: Marshon

copyright: Copyright &copy; 2026 Shang Ma

nav:
  - Index: index.md

theme:
    name: darkly

extra_css:
  - stylesheets/extra.css

plugins: []
